/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include <bootutil/sign_key.h>

#include <mcuboot_config/mcuboot_config.h>

/* The following is an ECDSA p256 public key in DER format that should be
 * generated from the same key that will be used to sign the device.
 */

/* clang-format off */

/* Autogenerated by imgtool.py, do not edit. */
const unsigned char ecdsa_pub_key[] = {
    0x30, 0x59, 0x30, 0x13, 0x06, 0x07, 0x2a, 0x86,
    0x48, 0xce, 0x3d, 0x02, 0x01, 0x06, 0x08, 0x2a,
    0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07, 0x03,
    0x42, 0x00, 0x04, 0xa6, 0xfb, 0x75, 0x1d, 0x35,
    0xa9, 0x79, 0x60, 0xbf, 0x62, 0x26, 0xaa, 0xc5,
    0x4e, 0x19, 0x32, 0xf4, 0xac, 0x31, 0xd1, 0x68,
    0x4b, 0xd9, 0xb2, 0x03, 0xa7, 0xd9, 0x06, 0x7e,
    0xac, 0x29, 0x8e, 0x5e, 0xf0, 0xd4, 0xe0, 0x3d,
    0xc7, 0xb3, 0xd8, 0x0a, 0xc6, 0x4e, 0x37, 0x90,
    0x57, 0x5d, 0x91, 0xcb, 0x88, 0x83, 0xa1, 0x7d,
    0x79, 0xef, 0xb3, 0xb0, 0xad, 0xf6, 0x4e, 0xe0,
    0x4e, 0xa2, 0x51,
};
const unsigned int ecdsa_pub_key_len = 91;

/* clang-format on */

const struct bootutil_key bootutil_keys[] = {
    {
        .key = ecdsa_pub_key,
        .len = &ecdsa_pub_key_len,
    },
};
const int bootutil_key_cnt = 1;
